title: Fenk Dev # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  i'm a late learner programmer trying to catch up to trying to reach a high level.  
  <br><br>
  (Python, NodeRed, IoT, Data Science, Machine Learning, Deep Learning, AI) 
  <br><br>
  <a href="https://www.linkedin.com/in/feny-suharyono-37a85839/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-7SESS8N56Q # your Google Analytics tracking ID here
